[tool.poetry]
name = "csv-reconcile"
version = "0.1.0"
description = "OpenRefine reconciliation service backed by csv resource"
authors = ["Douglas Mennella <douglas.mennella@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
flask = "^1.1.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
nose = "^1.3.7"

[tool.poetry.scripts]
csv-reconcile = "csv_reconcile:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
